name: url-shorten-mongodb

ports:
  - port: 27017
    targetPort: 27017

container:
  args: 
  - --config
  - /social-network-microservices/config/mongod.conf
  image: library/mongo
  imageVersion: 4.4.6
  name: url-shorten-mongodb
  ports: 
  - containerPort: 27017
  volumeMounts:
  - name: tls-cert
    mountPath: /etc/tls
    readOnly: true

volumes:
  - name: tls-cert
    secret:
      secretName: mongodb-tls

configMaps:
  - name: mongod.conf
    mountPath: /social-network-microservices/config/mongod.conf
    value: mongod

# tls:
#   mode: requireTLS
#   certificateKeyFile: /etc/tls/tls.pem
#   CAFile: /etc/tls/ca.crt

tls:
  mode: disabled
  certificateKeyFile: ""
  CAFile: ""

